

services:
  cd_service:
    image: cd_service:latest
    container_name: cd_service_container
    build:
      context: ../CBServiceAPI  # <- ret til den korrekte sti, hvis nødvendigt
      dockerfile: Dockerfile
    environment:
      - ToFail=yes
    ports:
      - "8080:8080" # internt i netværket, nginx bruger det
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "4000:8080" # porten til at tilgå nginx udefra
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cd_service
